# Generated by Django 5.0.2 on 2024-03-05 08:58

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="book",
            fields=[
                ("book_no", models.IntegerField(primary_key=True, serialize=False)),
                ("book_name", models.CharField(max_length=20)),
                ("author_name", models.CharField(max_length=30)),
                ("book_page", models.IntegerField()),
                ("book_price", models.IntegerField()),
            ],
        ),
    ]
